server:
  port: 8080
  servlet:
    context-path: /identity # bắt đầu của một URL

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root

  jpa:
    open-in-view: false # Tắt chế độ "Open EntityManager in View", để tránh lỗi lazy loading không cần thiết.
    hibernate:
      ddl-auto: update # Hibernate sẽ tự động tạo hoặc cập nhật bảng trong DB theo Entity. Giá trị khác: none, validate, create, create-drop.
    show-sql: true # Hiển thị câu lệnh SQL mà Hibernate chạy trong console (hữu ích để debug).
