@user = http://localhost:8080/identity

### API 1 - Test API create USER
POST {{user}}/users
Content-Type: application/json

{
  "username": "bang",
  "password": "12345678",
  "firstName": "Bang3",
  "lastName": "Bui3",
  "dob": "2004-10-10"
}

### API 2 - Test API get all user in the database
GET {{user}}/users

### API 3 - Find User by ID
GET {{user}}/users/8

### API 3 - Update User Information
PUT {{user}}/users/2
Content-Type: application/json

{
  "password": "12345678",
  "firstName": "Bang2",
  "lastName": "Bui2",
  "dob": "2004-10-10"
}

### API 4 - DELETE User By ID
DELETE {{user}}/users/2

### API 5 - Authenticate user
POST {{user}}/auth/log-in
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### API 6 - Verified token
POST {{user}}/auth/introspect
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJiYW5nYnVpLmNvbSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzUxMDI3ODYyLCJpYXQiOjE3NTEwMjQyNjIsInNjb3BlIjoiIn0.s34LNa2isyQPOlGeBSHIdBjcVp2HGDYLGHavVrWomh6avhkjxfmpLUruabYfwSRQ0i-BK2yV1xx0Kq_ZxhnuPg"
}

### API 7 - Get user with token
GET {{user}}/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJiYW5nYnVpLmNvbSIsInN1YiI6ImJhbmciLCJleHAiOjE3NTEwMzQyMjcsImlhdCI6MTc1MTAzMDYyNywic2NvcGUiOiJVU0VSIn0.KVpo3lIsoOFtgZdRTSNWvNeVzEI_GHNrQGrfIuxu-Ds-SgJBtcPSXZP1EX_Ifa0WoRFEOVloiKT_0-DdIH2I0Q

### API 8 - Get my info with token
GET {{user}}/users/myinfo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJiYW5nYnVpLmNvbSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzUxMDM0NTgxLCJpYXQiOjE3NTEwMzA5ODEsInNjb3BlIjoiQURNSU4ifQ.I-T7Tad7JvMnAJCQPyycSS1mJKN-_0k2u5j1AhjfMlYP6cB5Q3FqOcR-SngNKamKqDIwQSy6VezBxTTgJPgkaA