@user = http://localhost:8080/identity

### API 1 - Test API create USER
POST {{user}}/users
Content-Type: application/json

{
  "username": "bang4",
  "password": "12345678",
  "firstName": "Bang3",
  "lastName": "Bui3",
  "dob": "2004-10-10"
}

### API 2 - Test API get all user in the database
GET {{user}}/users

### API 3 - Find User by ID
GET {{user}}/users/8

### API 3 - Update User Information
PUT {{user}}/users/2
Content-Type: application/json

{
  "password": "12345678",
  "firstName": "Bang2",
  "lastName": "Bui2",
  "dob": "2004-10-10"
}

### API 4 - DELETE User By ID
DELETE {{user}}/users/2

### API 5 - Authenticate user
POST {{user}}/auth/log-in
Content-Type: application/json

{
  "username": "bang1",
  "password": "12345678"
}

### API 6 - Verified token
POST {{user}}/auth/introspect
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJiYW5nYnVpLmNvbSIsInN1YiI6ImJhbmcxIiwiZXhwIjoxNzUwOTQ5MDk1LCJjdXN0b21DbGFpbSI6ImN1c3RvbUNsYWltVmFsdWUiLCJpYXQiOjE3NTA5NDU0OTV9.5f5U99hTST_mU3Buda9IaHPJPxx1Vu037H27j4oEc6nFXRFfqv0iFbBacI6O9PWh_cIQ-ulko2XY-0WbuvWDrw"
}

### API 7 - Get user with token
GET {{user}}/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJiYW5nYnVpLmNvbSIsInN1YiI6ImJhbmcxIiwiZXhwIjoxNzUwOTUwMTYwLCJjdXN0b21DbGFpbSI6ImN1c3RvbUNsYWltVmFsdWUiLCJpYXQiOjE3NTA5NDY1NjB9.SprngSg0L2I7gaf1XCQ-svKNTc3eBtnBFLCnDbE2Ka1DBjI8zmSjugfIWJKN4lbHaN0oqXsuNw8maXqvlfpvuw
