@user = http://localhost:8080/identity

### API 1 - Test API create USER
POST {{user}}/users
Content-Type: application/json

{
  "username": "bang3",
  "password": "12345678",
  "firstName": "Bang3",
  "lastName": "Bui3",
  "dob": "2004-10-10"
}

### API 2 - Test API get all user in the database
GET {{user}}/users

### API 3 - Find User by ID
GET {{user}}/users/1

### API 3 - Update User Information
PUT {{user}}/users/2
Content-Type: application/json

{
  "password": "12345678",
  "firstName": "Bang2",
  "lastName": "Bui2",
  "dob": "2004-10-10"
}

### API 4 - DELETE User By ID
DELETE {{user}}/users/2